language: python
python: 2.7
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py32
    - TOX_ENV=py33
    - TOX_ENV=pypy
    - TOX_ENV=py26 CC=clang
    - TOX_ENV=py27 CC=clang
    - TOX_ENV=py32 CC=clang
    - TOX_ENV=py33 CC=clang
    - TOX_ENV=pypy CC=clang
    - TOX_ENV=py26 OPENSSL=0.9.8
    - TOX_ENV=py27 OPENSSL=0.9.8
    - TOX_ENV=py32 OPENSSL=0.9.8
    - TOX_ENV=py33 OPENSSL=0.9.8
    - TOX_ENV=pypy OPENSSL=0.9.8
    - TOX_ENV=py26 CC=clang OPENSSL=0.9.8
    - TOX_ENV=py27 CC=clang OPENSSL=0.9.8
    - TOX_ENV=py32 CC=clang OPENSSL=0.9.8
    - TOX_ENV=py33 CC=clang OPENSSL=0.9.8
    - TOX_ENV=pypy CC=clang OPENSSL=0.9.8
    - TOX_ENV=docs
    - TOX_ENV=pep8
    - TOX_ENV=py3pep8

install:
    - ./.travis/install.sh

script:
    - tox -e $TOX_ENV

after_success:
    - coveralls

notifications:
    irc:
        channels:
            - "irc.freenode.org#cryptography-dev"
        use_notice: true
        skip_join: true
